image: docker:latest

variables:
    DOCKER_DRIVER: overlay2
    PROJECT_BASE: "sssirsa/genesis"

services:
    - docker:dind

stages:
    - configuration
    - lint
    - deploy

configuration:
    stage: configuration
    image: quay.io/coreos/awscli:master
    script:
        - mkdir -p config
        - aws s3 cp s3://${BUCKET_S3}/deploy/${PROJECT_BASE}/${CI_PROJECT_NAME}/config/config.json config/config.json
        - aws s3 cp s3://${BUCKET_S3}/deploy/${PROJECT_BASE}/${CI_PROJECT_NAME}/deploy.js gulp/deploy.js
        - aws s3 cp s3://${BUCKET_S3}/deploy/${PROJECT_BASE}/${CI_PROJECT_NAME}/scripts.js gulp/scripts.js
    cache:
        untracked: true
        paths:
            - config/
            - gulp/deploy.js
            - gulp/scripts.js
    artifacts:
        paths:
            - config/
            - gulp/deploy.js
            - gulp/scripts.js
    only:
        - development
        - staging
        - master
        - merge_requests
    tags:
        - frontend

.lint_script: &lint_script
    stage: lint
    image: gitlab.sssirsa.com:9020/docker-images/frontend-image-libraries:${BRANCH}
    script:
        - mv /usr/app/* .
        - ./node_modules/.bin/gulp scripts
    dependencies:
        - configuration
    tags:
        - frontend

lint:all:
    <<: *lint_script
    variables:
        BRANCH: ${CI_COMMIT_REF_NAME}
    only:
        - staging
        - development

lint:test:
    <<: *lint_script
    variables:
        BRANCH: ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    only:
        - merge_requests

lint:latest:
    <<: *lint_script
    variables:
        BRANCH: "latest"
    only:
        - master

deploy:
    stage: deploy
    image: gitlab.sssirsa.com:9020/docker-images/frontend-image-libraries:${CI_COMMIT_REF_NAME}
    script:
        - mv * /usr/app
        - cd /usr/app
        - rm -rf dist/
        - ./node_modules/.bin/gulp deploy --env ${CI_COMMIT_REF_NAME}
    only:
        - development
        - staging
        - master
    tags:
        - frontend
