image: docker:latest

variables:
  DOCKER_DRIVER: overlay2
  PROJECT_BASE: "sssirsa/genesis"

services:
- docker:dind

stages:
- dep
- configuration
- deploy


configuration:
  stage: configuration
  image: python:latest
  script:
    - pip install awscli
    - mkdir -p config
    - aws s3 cp s3://file-production/deploy/${PROJECT_BASE}/${CI_PROJECT_NAME}/config/config.json config/config.json
    - aws s3 cp s3://file-production/deploy/${PROJECT_BASE}/${CI_PROJECT_NAME}/deploy.js gulp/deploy.js
  cache:
    untracked: true
    paths:
     - config/
     - gulp/deploy.js
  artifacts:
    paths:
     - config/
     - gulp/deploy.js
  only:
    - development
    - staging
    - master
    - hotfix/CorrectionGitCli

deploy:
  stage: deploy
  image: node:10.2.1
  before_script:
    - npm update socket.io
    - npm install fs-extra@4.0.1
    - npm install graceful-fs@4.1.11
    - npm i minimatch@3.0.4
    - npm install gulp
  script:
    - rm -rf dist/
    - ./node_modules/.bin/gulp deploy --env development
  dependencies:
    - npm
    - bower
    - configuration
  only:
    - development
    - staging
    - master
    - hotfix/CorrectionGitCli

npm:
  stage: dep
  image: node:10.2.1
  before_script:
    - apt-get update
    - apt-get install build-essential -y
  script:
    - npm install
  cache:
    untracked: true
    paths:
     - node_modules/
  artifacts:
    paths:
     - node_modules/
  only:
    - development
    - master
    - staging
    - hotfix/CorrectionGitCli

bower:
  stage: dep
  image: node:10.2.1
  variables:
    BOWER_VERSION: 1.8.4
  script:
    - ls
    - npm install -g bower@$BOWER_VERSION --silent
    - bower install --allow-root --silent

  cache:
    untracked: true
    paths:
     - bower_components/
  artifacts:
    paths:
     - bower_components/
  only:
    - development
    - master
    - staging
    - hotfix/CorrectionGitCli
