(function(){
    'use strict';

    angular
        .module('app')
        .factory('SalePointRequests',SalePointRequests);

    function SalePointRequests(){
        var api = 'http://genesis-mobile-dev.sssirsa.com:8000';
        //var baseUrl = Restangular.allUrl('',api);

        var objects = [
            {
                "id": 9,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T00:40:36.152222Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 10,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T00:46:18.896401Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 12,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Recolección",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T00:51:40.564576Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 13,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Servicio Técnico",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T00:51:52.525855Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 19,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T01:25:30.142039Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 23,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Recolección",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-11T00:26:55.181218Z",
                "calificacion": 0,
                "status": "Atendida",
                "fecha_atencion_cliente": null
            },
            {
                "id": 25,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Servicio Técnico",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-11T00:48:25.489270Z",
                "calificacion": 0,
                "status": "Atendida",
                "fecha_atencion_cliente": null
            },
            {
                "id": 24,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 9,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 10,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-11T00:43:58.019083Z",
                "calificacion": 0,
                "status": "Atendida",
                "fecha_atencion_cliente": null
            },
            {
                "id": 17,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 5,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 6,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T01:22:11.954098Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 26,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 11,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 12,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/prospectacion/ines/front/IBHZAPWB4NP5NCSWQDCI83G0LAN6HMYNWKZQXL19I5WLS717UV.jpg?Signature=%2BRfXqGt9IpvnRCEoafvP8HQmmMk%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/prospectacion/ines/back/0AZGUOLI1GZOPBTE9FGH9YQGVFM26MS8HHNGMKKIFSAX1H3FXC.jpg?Signature=Nk%2FgfkTbmDpqFX0G%2FOMpz1UeTQI%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/prospectacion/establecimiento/foto/BGCZDSOAINZ6URKDJN8000T0XR58ISCMV2ZTXZ7AEW1V5DI5BQ.jpg?Signature=3UaaTL4a1vjU1Lnva59EMf6Zk6k%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/prospectacion/establecimiento/comprobante/26JHT9XIARNSVSALA7UQ31O7SI5GGUNP1HFUX7F3V7ELTW1Y9J.jpg?Signature=rXPYqk7NMnRfvdnPeiG6u52A3rU%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-11T07:16:11.579212Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 32,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 15,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 16,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-13T08:10:52.855343Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 37,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_50a12adb-8e88-4ef3-a341-86ce9918c22f_.jpg?Signature=9nfAAtucvKIfVa0pAphgXosswT8%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_3e82ec2c-989b-4afa-a87d-a494d8270fde_.jpg?Signature=3qXEUwz3cxLpMNx8PuSF1ugNUzY%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_7fc98c76-422d-47e5-9068-29ea3f561fb3_.jpg?Signature=qTtdNlWx3PNJ220QgXgaafhLgRw%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_169ae794-2693-4bf7-a8b5-1f7197a7bbae_.jpg?Signature=0R%2BZ41v4anvyAtnFi8fPoBOTAAw%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 23,
                "calle": "CalleBaca",
                "numero": "1",
                "entre_calle1": "CalleC",
                "entre_calle2": "CalleD",
                "cp": "92540",
                "fecha": "2017-10-02T20:59:20.652055Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 20,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T02:03:46.403251Z",
                "calificacion": 5,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 39,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_97233ec2-02a2-4d91-adcf-b30031b51821_.jpg?Signature=pYVzpB%2FMcebMsZxy4h8rnWYslZ8%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_eb023502-e0ca-43cd-8e1c-8e9722558d81_.jpg?Signature=VAhtm68OpA%2BrT6ESIenuAFwQLHg%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_837da344-4f7f-41db-98ba-50ce6f3dcdec_.jpg?Signature=q4JevZne%2FIt8zRyy%2FrUUnWKfzPQ%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_f4419752-932c-45fe-ab48-193f33f48b03_.jpg?Signature=gqSJbTJUEq5hVd0bIowgVQuwqQ4%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.531969",
                "longitud": "-99.167000",
                "precision": 23,
                "calle": "Cuitlahuac",
                "numero": "76",
                "entre_calle1": "Chimalpopoca",
                "entre_calle2": "Cuitlahuac privado",
                "cp": "54150",
                "fecha": "2017-10-02T22:49:34.950675Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 40,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_c803144d-fd67-40c0-be0d-6889e03edbd6_.jpg?Signature=np%2F8m3TJ%2Bs6A1CIqmGkNJaMWpuU%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_f6127648-d697-4ea7-b01c-78fbc763bcac_.jpg?Signature=zicf9g3gPx66YUddP7dE87ah7to%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_a3ee1ad9-c62b-4caa-9c7e-5ffd0c958319_.jpg?Signature=xoNl8zI5lD4gOzSxMMO8FahocAE%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_bd90f7b4-063f-4ead-b232-25cf37518b08_.jpg?Signature=NHLQmfHJxN5%2F36k9mGkD2nsh76Y%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Incremental",
                "latitud": "19.531969",
                "longitud": "-99.167000",
                "precision": 20,
                "calle": "Cuitlahuac",
                "numero": "76",
                "entre_calle1": "Chimalpopoca",
                "entre_calle2": "Cuitlahuac privado",
                "cp": "54150",
                "fecha": "2017-10-02T22:52:26.718823Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 41,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 19,
                        "tipo": "AT2",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_d321e35f-c7a1-4015-a382-cd25fbdb517d_.jpg?Signature=Y26gp4OWWlVFuGJpZWpOP0S5b%2FE%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_4e760dd9-5051-4cfa-924c-27d10100c630_.jpg?Signature=mrSLaZUIGZaSLSBFZnmgZYxTimQ%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_d06d50d5-d2f5-4451-aa4e-a769a291339c_.jpg?Signature=OYo3%2BQ3oF7%2BnWDe8ny4owqPgZBM%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_660c2711-e265-4fbc-94fc-7a4d744964c6_.jpg?Signature=r4Ld83L9dQL5uqSLM3W%2BgA5tY9w%3D&Expires=1507100639&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.531969",
                "longitud": "-99.167000",
                "precision": 21,
                "calle": "Cuitlahuac",
                "numero": "76",
                "entre_calle1": "Chimalpopoca",
                "entre_calle2": "Cuitlahuac privado",
                "cp": "54150",
                "fecha": "2017-10-02T22:54:06.446985Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 42,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 20,
                        "tipo": "AT2",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_5310208b-616d-4eb5-8d6b-7bf4834d897b_.jpg?Signature=Htzom7wr3IvSq5erhVoSL6RI3nU%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_aeead133-b8a4-4878-bd36-89e958652313_.jpg?Signature=sF4Ez2cOdp8v46Aw%2FwFa7Vp%2FSoI%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_af74859e-5f04-4073-bd72-0b25cae47b26_.jpg?Signature=XfBEBTGADFnzDmwLdq8EHhLiy3E%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_a77b021e-dca4-4f95-a719-353ef35f1c2f_.jpg?Signature=k%2BAA0734uY0fE74z5J1Q7kQiXhM%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "19.493339",
                "longitud": "-99.019034",
                "precision": 23,
                "calle": "Cerro de la sikla",
                "numero": "M3 L46",
                "entre_calle1": "Guadiana",
                "entre_calle2": "Sagitario",
                "cp": "55238",
                "fecha": "2017-10-02T23:49:09.806349Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 43,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_564897c3-a27b-4321-b06c-9f851502ebc0_.jpg?Signature=LW9aWUIMdyFGxdmgI1%2FpS77ryCk%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_1056eff1-dfc8-4073-8152-57dc4d3a7f33_.jpg?Signature=noE6vxfXiqBQVvu%2FFQBZel%2FFAAA%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_fa52a170-8365-49a3-83d6-e87b5cbb2e72_.jpg?Signature=MnwixccIp70qjljNiR6EEN4NgGo%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_350b45c1-adf5-4b69-8130-62155986a392_.jpg?Signature=aVWiSpUJeS3i2gVcjE1ZgGlebMI%3D&Expires=1507100640&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Recolección",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 23,
                "calle": "Sn",
                "numero": "Zn",
                "entre_calle1": "Sn",
                "entre_calle2": "888",
                "cp": "89098",
                "fecha": "2017-10-03T12:39:50.831575Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 33,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 17,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 18,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-13T08:13:36.383627Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 35,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleBr",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-10-01T05:18:01.988025Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 15,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 1,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 2,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T01:13:24.562739Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 21,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 7,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 8,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-10T21:32:16.842185Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 27,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 13,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    },
                    {
                        "id": 14,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-13T01:47:46.097116Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 38,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_11a8125a-c554-4c60-8f6a-20f8ab4713f9_.jpg?Signature=UBvF2G12lJSG3zmUuOM9i3XIgU8%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_320abc68-8fc4-4a27-8a99-22158b97f32f_.jpg?Signature=FtX425s36dafvc7s8Z5gxU9ybNQ%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_f0392548-1de7-44e3-a92c-d8d99d1e2930_.jpg?Signature=Q6CZuy4%2B7FPFlKhpT2YUR1mWKaY%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_dab565cb-7545-44c6-aca9-0eff29de2755_.jpg?Signature=YOH54EvYDhWZqBbAcbYgW1rqIDE%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Incremental",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 23,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-10-02T21:01:09.832591Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 11,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Recolección",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-08T00:49:54.727097Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 22,
                "persona": 3,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": null,
                "ine_back": null,
                "foto_local": null,
                "comprobante_local": null,
                "deleted": false,
                "tipo": "Cambio",
                "latitud": "0.000000",
                "longitud": "0.000000",
                "precision": 0,
                "calle": "CalleB",
                "numero": "12b",
                "entre_calle1": "CalleA",
                "entre_calle2": "CalleC",
                "cp": "59023",
                "fecha": "2017-09-11T00:11:20.587052Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 36,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_e6cffc78-ad9f-4f3e-a061-6141c1cccea8_.jpg?Signature=uAWg4J22DKwcDypSdUcuY8DBWX0%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_6c637a09-b4fd-4e1f-888c-c98e48a28af5_.jpg?Signature=iOHCGbsUCHipZcjsTEJw2dGjOMg%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_8de00174-f671-456b-8062-912655b72c92_.jpg?Signature=LS40PZqjK%2B%2BV1dGmLUULfbd7pN4%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_7a26dd22-ae77-41f8-bae3-ab43ad3426c1_.jpg?Signature=2kWoHMJp5AiVgieVvYl7JV3PXm8%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 24,
                "calle": "CalleBaca",
                "numero": "1",
                "entre_calle1": "CalleC",
                "entre_calle2": "CalleD",
                "cp": "92540",
                "fecha": "2017-10-02T14:34:20.491659Z",
                "calificacion": 0,
                "status": "Cancelada",
                "fecha_atencion_cliente": null
            },
            {
                "id": 44,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 21,
                        "tipo": "AT1",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_6544d9b4-9a09-40e9-8533-ab84b254a804_.jpg?Signature=hfiAcQbCqXgzQlEsuX1bNKDJN%2F8%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_beba9314-4075-4015-be1e-a37542cb3b19_.jpg?Signature=tac0051PhPyodMp4yxrDcVmgSJ4%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_664695e1-b4a6-487b-b8e8-a7d234fb283b_.jpg?Signature=rKJDiHW5ayLIri7Ji61kUKuUYJU%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_a2f058b4-1dfd-4c6d-84a6-54e4e22830a4_.jpg?Signature=Fxnq3dQEEbzjDq%2BLDTebwtsXUg8%3D&Expires=1507100641&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.504325",
                "longitud": "-99.147367",
                "precision": 23,
                "calle": "Sn",
                "numero": "Zn",
                "entre_calle1": "Sn",
                "entre_calle2": "888",
                "cp": "89098",
                "fecha": "2017-10-03T16:45:11.561641Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 45,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 22,
                        "tipo": "Bicicleta",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_71ecff4c-4f23-4eaa-ac87-faa5adaf2323_.jpg?Signature=Q3LC5T2sG1wNRrYjA2rrZVhV1S4%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_4f2036d4-d8be-459d-a894-f3ffd2292605_.jpg?Signature=Nz%2FrV60%2B%2FtXEhXhieZGbe1zEvZM%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_bc25c2e7-bfb7-45b3-987b-730526c112ca_.jpg?Signature=iBLrw0UXZhhTRDKuOG66lHUlOp0%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_be661817-5596-4932-952a-986ea1601f29_.jpg?Signature=Z9U6hFHy%2FHUTzOPq%2BkWBfvJMHYA%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 23,
                "calle": "Plata",
                "numero": "43",
                "entre_calle1": "Paladio",
                "entre_calle2": "Cadmio",
                "cp": "48447",
                "fecha": "2017-10-03T23:14:24.181104Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 46,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 23,
                        "tipo": "AT3",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_e4dca15b-59d8-4d2d-8809-ab1c84ea549c_.jpg?Signature=XLoFvQlb5yO55CqqYH%2B53NjDryE%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_942650e4-01e0-4578-af31-33b889ff7935_.jpg?Signature=HCgIWogpkylbPvoaAaDUQObY%2F7M%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_cd521c4f-a269-47b2-b8ea-af52726a0960_.jpg?Signature=0tX3MXpKFaXLYp0mEfk8tPfcPD0%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_9b8f0b92-d343-42d8-bdf7-4356749b427b_.jpg?Signature=VBeGPSGAsI4GmiO%2Fj2yp%2FtD8jdM%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Incremental",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 23,
                "calle": "Cerro del chiquihuite",
                "numero": "68",
                "entre_calle1": "San juan gregorio",
                "entre_calle2": "Chimalpa",
                "cp": "88790",
                "fecha": "2017-10-03T23:17:51.564342Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 47,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_7f3c94df-aa9e-4568-8db6-ebb18cd817e9_.jpg?Signature=INFMnYABnM0Fwrt9UU34IVpOt5A%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_59bbe56d-dacf-4f80-b471-abfd5d28c77b_.jpg?Signature=sYjnTbYojP%2BDGcrmQMtKDB1TDmw%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_ae8787d6-7148-4269-ba5b-eb825f3b75a7_.jpg?Signature=o3cha8obrpAMOyBoaP57mbsO7k4%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_fb623ce0-ab9a-425a-940c-97781c41b791_.jpg?Signature=xT8D83x7tAeaV00RwqBIyu0QoJA%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Recolección",
                "latitud": "19.504336",
                "longitud": "-99.147377",
                "precision": 50,
                "calle": "Sn",
                "numero": "Zn",
                "entre_calle1": "Sn",
                "entre_calle2": "888",
                "cp": "89098",
                "fecha": "2017-10-03T23:33:33.404677Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            },
            {
                "id": 48,
                "persona": 4,
                "cabinet": null,
                "establecimiento": null,
                "solicitudes_cabinet": [
                    {
                        "id": 24,
                        "tipo": "Tapa de cofre",
                        "deleted": false,
                        "antiguedad": null,
                        "cantidad": 1
                    }
                ],
                "ine_front": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/front/ine_front_dc889857-e9d2-42c2-9942-c5c5327fb6b7_.jpg?Signature=Z%2B%2FFv3LUYhSEj4cVb1q%2BqTvQZl4%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "ine_back": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/ines/back/ine_back_18e39905-1ba0-4382-91c4-d2726e16e129_.jpg?Signature=obEjlwkowAYWW9xL0lIFwVEY8bA%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "foto_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/foto/foto_local_16b4bbf5-deee-476a-8742-703d82feee0d_.jpg?Signature=fp6%2FCw7SN4LBGq0kectvV4Pbnlc%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "comprobante_local": "https://sssirsa-mobile-dev-documents.s3.amazonaws.com:443/servicio/establecimiento/comprobante/comprobante_local_21a127e0-7bf5-4e7d-bfc6-0dbeffb8bfa7_.jpg?Signature=L4HgAh4wjSjhNBsQKF7xVKxGiqU%3D&Expires=1507100642&AWSAccessKeyId=AKIAIITVBJH7HAF5W5XA",
                "deleted": false,
                "tipo": "Nuevos",
                "latitud": "19.493327",
                "longitud": "-99.019044",
                "precision": 24,
                "calle": "Cerro de la sikla",
                "numero": "M3 L46",
                "entre_calle1": "Guadiana",
                "entre_calle2": "Sagitario",
                "cp": "55238",
                "fecha": "2017-10-04T05:30:45.091693Z",
                "calificacion": 0,
                "status": "Abierta",
                "fecha_atencion_cliente": null
            }
        ];

        var service = {
            getByID:getByID,
            getAll:getAll
        };

        function getByID(id){
            //return baseUrl.one('solicitud',id);
            return _.where(objects, {id: id});
        }

        function getAll(){
            return objects;
        }

        return service;
    }

})();
